### PR TITLE
Twitter Meme Template added

### PR DESCRIPTION
**Pull request by laxyapahuja**
app/src/main/res/layout/twitter_meme_layout.xml

### CODE REVIEW

**Comment by laxyapahuja** [comment]
ss Screenshot of how it looks like
twitter Actual twitter post

**Comment by laxyapahuja** [comment]
Image will be fitted in the same resolution as the image in the "actual twitter post" so there will be white borders if the image uploaded by user will be different than the resolution. I have done that too.

**Comment by padamchopra** [comment]
@laxyapahuja Next time try to edit your original PR description instead of adding so many comments. This spams the maintainer of the organizations as we get emails regarding each of the comment. Also, learn to make xml through `code` and not by `drag and drop`. We'll be reviewing the PR shortly :wink:

**Comment by padamchopra** [comment]
### Your version gave the following errors on build
screenshot from 2018-02-07 20-52-22

**Comment by laxyapahuja** [comment]
added the scrubber.png and removed the untracked files.

**Pull request closed without merging**
